[project]
name = "vi-pll"
version = "0.1.0"
description = "This repository contains the code and data of the paper 'Variational Inference for Partial-Label Learning'."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cuda-selector>=0.1.5",
    "joblib>=1.5.3",
    "pandas>=3.0.3",
    "requests>=2.34.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "tabulate>=0.10.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "tqdm>=4.67.3",
    "types-requests>=2.33.0.20260508",
    "types-tqdm>=4.67.3.20260508",
]
